### ISSUE TITLE
Problem with downloading data from site

### ISSUE THREAD

**Issue by KrzysztofKaluza** [corochann/chainer-pointnet#3]
However, I have a problem that by downloading data from the site http://buildingparser.stanford.edu/dataset.html#Download   for segmentation, throws a network error, sorry for polish on pictures, first one says failure - network error, resume, and second one
failure - requires authorization 
![err1](https://user-images.githubusercontent.com/38680423/65587825-c843a980-df86-11e9-9a2b-cc7472095ccf.PNG)
![err2](https://user-images.githubusercontent.com/38680423/65587832-cda0f400-df86-11e9-8f00-f93dfc28371b.PNG)
it is from one downloading session,

**Comment by corochann** [comment]
I feel it looks like your internet connection env problem,,, did you try downloading the data in several internet connection environment? For example, university internet may block heavy content downloading etc.

**Comment by KrzysztofKaluza** [comment]
I'm trying to download it at home, but I'll try to download it from a different network and see how it works

**Comment by KrzysztofKaluza** [comment]
solved, I did not see the second link, from google drive I have downloaded it without problems

**Comment by corochann** [comment]
Glad to hear that. Then let me close the issue.
